site_name: SniffHound Docs
site_description: Documentacion oficial de SniffHound
site_author: SniffHound Authors
site_url: https://sniffhound.jorgelsc.dev/
repo_url: https://github.com/jorgelsc-dev/sniffhound
repo_name: SniffHound
edit_uri: edit/main/docs/

nav:
  - Inicio: index.md
  - Empezar: getting-started.md
  - Arquitectura: architecture.md
  - Ayuda:
      - Resumen: help/index.md
      - Modos: help/modes.md
  - Referencia:
      - Resumen: reference/index.md
      - Runtime: reference/runtime.md
      - Auth: reference/auth.md
      - Persistencia SQLite: reference/persistence.md
      - API y WS: reference/api.md

theme:
  name: material
  language: es
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      primary: teal
      accent: amber
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - toc:
      permalink: true

extra_css:
  - assets/stylesheets/extra.css
